name: 'Label PR Size'
description: 'Labels PRs based on their size.'
author: 'Luke Hinds'
branding:
  icon: 'tag'
  color: 'blue'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  base-sha:
    description: 'Base SHA of the PR'
    required: true
  head-sha:
    description: 'Head SHA of the PR'
    required: true
  repository:
    description: 'GitHub repository'
    required: true
  pr-number:
    description: 'Pull request number'
    required: true
